### ISSUE TITLE
No ip support

### ISSUE THREAD

**Issue by MD5-Hashm** [py-mine/mcstatus#216]
As title states this lib requires you to use a hostname with no ip support...

**Comment by ItsDrike** [comment]
We don't require hostname only, using IP is already possible.

The `MinecraftServer.__init__` takes `host` and `port` arguments, where `host` can be a domain, but it can also be an IP, there's no requirement to only allow a domain there. Initialization like: `my_server = MinecraftServer("192.168.0.105", 25565)` is completely valid and should work (assuming the IP points to a valid minecraft server).

This is also the case for the `lookup` function, which basically mimics the address field in minecraft. You can simply use `my_server = MinecraftServer.lookup("192.168.0.105:25565")`, and you can even drop the `:25565` since that's the default port and it's assumed if no other port was specified: `my_server = MinecraftServer.lookup("192.168.0.105")`. But agian, this doesn't mean you can only use an IP here, nor does it mean you can only use a domain, you can use both, and `my_server = MinecraftServer.lookup("mc.hypixel.net")` would also work just fine.
