### ISSUE TITLE
Consider slice async logic to its own classes

### ISSUE THREAD

**Issue by PerchunPak** [py-mine/mcstatus#418]
This continues a discussion from #377.

We ended on waiting for @kevinkjt2000's mind.

**Comment by kevinkjt2000** [comment]
All of this to save typing `async_` for some methods? In favor of typing `Async` once? Hardly seems worth it to me. What do we gain by moving stuff around like this? Will the user experience improve in some way or will they be irritated at having to change their code for seemingly no gain? Will developer experience improve in some way?

Regardless of the method, there are going to still be two implementations because of how Python is designed and because mcstatus is not going to force async-only usage. From what few libraries I've interacted with that have `async` functions, I see that most of them get around this issue by only having a single implementation. In other words, they are forcing users to learn how to handle asynchronous programming in Python. I would like to hold off for now on enforcing that in mcstatus.
