### ISSUE TITLE
How would I await the functions?

### ISSUE THREAD

**Issue by TomSipsOnCurry** [py-mine/mcstatus#429]
I remember this used to have an async alternative but now I cant find the function.

**Comment by ItsDrike** [comment]
Most of the async alternatives are simply prefixed by `async_`, here's a simple example:

```python
import asyncio
from mcstatus import JavaServer

async def main():
    server = await JavaServer.async_lookup("mc.hypixel.net")
    status = server.async_status()
    print(status.description)


asyncio.run(main())
```

**Comment by TomSipsOnCurry** [comment]
Oh, thank you. I just want to ask how I would get the player list without using query. Because when I used this before I remember doing it with status.

**Comment by PerchunPak** [comment]
Try this with example by ItsDrike

```py
if status.players.sample is not None:
    players = [player.name for player in status.players.sample]
else:
    players = []
```

Note that this can be empty as well as contain some advertisement by server.

**Comment by TomSipsOnCurry** [comment]
For some reason tis always returning none

**Comment by PerchunPak** [comment]
Are you trying one server?

**Comment by TomSipsOnCurry** [comment]
Yes

**Comment by PerchunPak** [comment]
So you will always get the same result. This depends on server's configuration, and if it didn't change - result also will not change.

**Comment by ItsDrike** [comment]
Yeah, the player sample is not a perfect solution, it's often going to be incomplete and might only include first few players, or even completely empty, because many servers run plugins to hide it, especially the bigger ones.

In some cases, these plugins can even alter the player sample to contain fake players for purposes of advertisement, so for example there might be a player named "SkyBlock now updated!", or similar things. 

Using status for getting player names is very unreliable, however it's the best option you have if the server doesn't support query. For vanilla servers, using sample should work without issues.

**Comment by TomSipsOnCurry** [comment]
It's my server. I dont want to use query because i'm making a discord bot and since query takes more than 3 seonds the discord.py interaction times out.

**Comment by PerchunPak** [comment]
Then you should find how to enable players list while hovering their count in servers list.
![image](https://user-images.githubusercontent.com/68118654/197535463-a98a4ff0-3793-4e30-b6b7-705be6953887.png)

**Comment by TomSipsOnCurry** [comment]
> Then you should find how to enable players list while hovering their count in servers list on your core. Do not use plugins, it's already implemented even in Vanilla. ![image](https://user-images.githubusercontent.com/68118654/197535463-a98a4ff0-3793-4e30-b6b7-705be6953887.png)

It works

**Comment by TomSipsOnCurry** [comment]
> @TomSipsOnCurry
> 
> > query takes more than 3 seconds
> 
> Because there is either a firewall or query was not enabled in server.properties.

I use a server hoster, but I enabled query

**Comment by TomSipsOnCurry** [comment]
Nvr mind turns out i put the wrong port :(
