### ISSUE TITLE
Automatically publish to PyPi on tag triggers

### ISSUE THREAD

**Issue by kevinkjt2000** [py-mine/mcstatus#490]
This enables #488 to proceed without worrying about local releases. Releasing from the pipeline shall make use of the PYPI_TOKEN variable that has already been added to secrets. The release step shall depend on all the other quality checks to pass before executing. The release.sh script must be removed as part of this too.

**Comment by ItsDrike** [comment]
We could just replicate [mcproto:.github/workflows/publish.yml](https://github.com/py-mine/mcproto/blob/main/.github/workflows/publish.yml) workflow for this, without the changelog stuff, although I'm not entirely sure what would be put into the generated github release comment then.

With mcproto, the changelog is automatically obtained from changelog fragments, which are required for every PR, this is done using [`towncrier`](https://pypi.org/project/towncrier/), we could replicate this too if we wanted it. Check [mcproto:changes/readme](https://github.com/py-mine/mcproto/blob/main/changes/README.md) for some info on how it's used.

**Comment by kevinkjt2000** [comment]
I foresee GitHub releases still being manually created for the time being. The resulting tag push that accompanies one would spark this GitHub action I'm proposing.

**Comment by ItsDrike** [comment]
Oh, in that case, it should be easy enough to just remove those steps and steps obtaining the changelog from the action, and use the rest as-is.

**Comment by PerchunPak** [comment]
I would like to have auto generated changelog, especially if it takes less work to add it, instead of removing it.

**Comment by kevinkjt2000** [comment]
GitHub release creation page nearly automates changelog. I'm only removing dependabot commits at this point.

**Comment by PerchunPak** [comment]
Towncrier will automatically follow [Keep a ChangeLog](https://keepachangelog.com) format, which is basically much better than we have now.

**Comment by ItsDrike** [comment]
Indeed, using towncrier for changelog can be pretty neat, and it can then even be integrated into the docs, see [mcproto changelog page in docs](https://mcproto.readthedocs.io/en/latest/pages/changelog/), or just directly in [`CHANGELOG.md`](https://github.com/py-mine/mcproto/blob/main/CHANGELOG.md).

That said, this does add yet another additional tool the contributors will need to understand, and as long as the PRs describe what they do in their title meaningfully enough, it will be captured in the generated changelog by github well enough.

But yes, a changelog will lessen the effort of having to decide on what's a breaking change, what's an internal one, which PRs should be included, potentially having to modify the title in the changelog, etc. as this process would be moved to simple PR reviews, and the final version can then be put together with a workflow, creating a PR by a bot account, adding up all of the changelog fragments into the `CHANGELOG.md` file, as an example, see: https://github.com/py-mine/mcproto/pull/16.

**Comment by kevinkjt2000** [comment]
Maybe I am being sentimental about this, but I like clicking the create release button and deciding on the next version. 

Let's take incremental steps to eventually adopt automated releases. This issue is about accomplishing the first step by publishing to PyPi when a tag trigger prompts it to. Later, we could implement an action that generates a changelog automatically and creates a GitHub release which would cascade into creating a tag that releases to PyPi. It would be convenient if every merge into a protected branch triggered a release if the changelog generation is non-empty.

After those steps, I feel that would be the moment to evaluate if the actions could be shuffled around or combined in some way to avoid any repeat action runs.

**Comment by PerchunPak** [comment]
> ... Later, we could implement an action that generates a changelog automatically...

The problem is that auto changelog has already implemented in mcproto, so I do not see any reason to remove it from an already ready to use system. Like we can just copy and paste **all** the files, without any modifies, and it will be much better than any other option.

> It would be convenient if every merge into a protected branch triggered a release if the changelog generation is non-empty.

It would be difficult and annoying. Merging some PR triggers CI, that will want to modify *protected* branch. But as it's *protected*, no-one can modify it - CI must open PR. Such PRs would be a lot, because it will need to modify the changelog on almost any PR merge. Do we really need this?

Also, it's quite more than just automated releases. Maybe open a new issue about rendering changelog inside CHANGELOG.md file, and now just update it in ReadTheDocs build only? Something like mcproto currently does, just CHANGELOG.md there only points to docs.

If you want to keep changelog as markdown file (which is quite useful for dependabot, as it is rendered in bump PRs), for now, we can just mention docs as more up-to-date version. This string can be removed in "Prepare for release" PR, but I do not really know where to add it back, as we use `poetry-dynamic-versioning` and so we do not need "Return dev version" PR. I think, in such case, it's okay to just keep the string without removing it in released versions. Maybe it shouldn't only be mentioned on the GitHub Release page.

**Comment by kevinkjt2000** [comment]
Hopefully, this provides some clarity around some of the ideas I have for the future of automatic releases in this repo.

Adding commits to version control as part of a pipeline is a big nope for me. I've been bitten by this enough times to learn why that is always a bad idea. This is why I now always try to adopt `git describe` for discovering the version to avoid checking in a version bump into git. Git is smart enough to give me the version without me having a file in there that constantly has conflicts. Storing a changelog as a checked-in file would also have constant churn (and therefore conflicts).  

But, we could still dynamically generate a changelog if it is intended for a GitHub release description and not to be added to version control. This changelog data would come from git commit messages. Admittedly those would have to be in a somewhat specific format, and this closely aligns with what I'm already doing manually when I make a new release on GitHub and use the auto-generated changelog. If all the commits are dependabot bumps, no new tag is going to be created, because no changelog messages would be worth creating a new GitHub release for. This is the same as what I do today when I trim out all dependabot changes to remove that extra noise from a GitHub release. Next, I evaluate what each PR did and decide if it was major, minor, or patch. Commit messages could contain data to automate this, and there is no need for all contributors to be aware of this because we could sneak in empty commits that contain a message instructing that we would like a major bump. In fact, we could do this as part of editing a squash commit message. Possibly enforcing that some regular expression matches the squash message. After that manual commit inspection, I then make a GitHub release with a tag I choose based on the inspection and generate the automatic changelog minus dependabot.

Short summary of the future:
1. Commits are sent via PR
2. PR is squash merged with a specific string instructing what type of version it gets
3. At our leisure or perhaps automatically, an action is triggered that releases everything between the last release and the commit the action is running on
4. Changelog generated and if there are some changes worth releasing, a GitHub release is created
5. GitHub release creates a tag that prompts the action for uploading to PyPi

This issue is about that part of step 5 where a new tag triggers an upload to PyPi.

**Comment by ItsDrike** [comment]
I'm not sure there's a way to enforce squash merge message to follow a regex in github. We could probably make a git hook to handle it if merging would be done via git, but I doubt github has such functionality. We could do merging with git manually, but this gets annoying with forks, so I'm not a huge fan of having to do that.

Without any enforcement of some pattern in the squash message, I wouldn't really trust myself to not make any accidental mistakes when merging PRs like this. Since this goes directly to master, force pushing to fix isn't really an option, and I'm not sure if an automated workflow here would then allow us to fix such issues easily.

Also, as we've seen recently, some PRs can be pretty big, and squashing might not always be what we want to do, as it can sometimes be handy to retain the git history of that branch, as it was developed. More commits, if they're well structured, can provide benefits like when doing a `git bisect` to find issues. Preserving the commit history is also nice for `git blame`, and other utilities.

---

We could go with the blank commit route, and require all contributors to leave "enable changes from maintainers" on in the PRs, so we would be able to push new commits to their code, once we'll be merging. This solves the issue of potentially wanting to preserve commit history, but again, it can be pretty annoying to have to do for each PR as maintainers.

What could be a cool solution is considering using github PR labels for `breaking`, `minor`, `patch`, `internal` or similar and then somehow collecting the PRs involved in a release, and figuring out what version needs to be bumped based on these. I'm just not sure how possible it would be to get all of the PRs since the last release, but it should probably be doable, afterall github does this internally already.

We could then simply use the PR name, which is editable by maintainers, or/and the PR  description in the final changelog. Avoiding the need to pushing weird blank commits into the history just for the sake of CI picking them up, or squashing every PR and following a very specific pattern for it's commit message.

**Comment by kevinkjt2000** [comment]
I like this idea of labeling. I believe it should be possible to add an enforced check that validates the presence of certain labels before a pull request can be merged. GitHub is already collecting all PRs since the last release when it generates automatic release notes, so there must be some mechanism it is using. Probably something from the merge commits that have the title and id of each PR.

**Comment by PerchunPak** [comment]
PR description shouldn't go to the changelog. It can contain some instructions to review or reproduce the problem (if a problem cannot be reproduced with pytest without mocking) or other unnecessary after merge things.

I still prefer to force the PR author to create a file, which will go to changelog. We are small enough to not support multiple versions at one time (so changelog generations will not conflict), and even if we would, it's possible to render the changelog only in docs, then in `CHANGELOG.md` reference to them.

This approach will also avoid custom tools writing, as those exist already.

**Comment by kevinkjt2000** [comment]
> PR description shouldn't go to the changelog.

Did I say PR description? If I did, I meant PR title. Which is something maintainers can easily modify before a merge.

> I still prefer to force the PR author to create a file, which will go to changelog

Git's history is the definitive changelog. Generating from the history is fine for posting to docs or GitHub releases.

> We are small enough to not support multiple versions at one time

Multiple PRs come in simultaneously; this is the same as having multiple versions. I guarantee from my experience that editing the same file will inevitably have repeatedly annoying conflicts. While these conflicts are often easy to resolve, they grate on nerves slowly over time like sand in shoes after walking alongside a beach.

Once version information is dynamically pulled from source control in a project, there is no amount of convincing that will sway me to undo that. Mcstatus is already dynamic with poetry-dynamic-versioning, so I will not let us add changelog.md into code and regress to a previous state where I was bumping versions in text files.

**Comment by ItsDrike** [comment]
> Multiple PRs come in simultaneously; this is the same as having multiple versions. I guarantee from my experience that editing the same file will inevitably have repeatedly annoying conflicts. While these conflicts are often easy to resolve, they grate on nerves slowly over time like sand in shoes after walking alongside a beach.

This actually isn't that big of an issue with tools like towncrier, as you don't actually have the users modify the actual `CHANGELOG.md`, causing conflicts, instead, you have them create changelog fragments, which are standalone files, which then get put together into a changelog automatically, by running a towncrier command.

So this means that the contributors would just be required to add a new file named something like `53.feature`, or `53.breaking` (or both), which signifies that PR 53 added a feature/breaking change, or whatever other category we choose to define. It's actually a pretty clever approach to do it.

> Once version information is dynamically pulled from source control in a project, there is no amount of convincing that will sway me to undo that. Mcstatus is already dynamic with poetry-dynamic-versioning, so I will not let us add changelog.md into code and regress to a previous state where I was bumping versions in text files.

Actually, I use poetry dynamic versioning in mcproto, and it uses towncrier changelogs. The way this works is pretty simple, you just go to workflows, and run that workflow, giving it a version in a prompt that appears from github as you click the run workflow button.

![image](https://user-images.githubusercontent.com/20902250/232131445-d169898e-3a2e-4831-beaf-9f955b0bd989.png)

However I'm sure we could use poetry dynamic versioning or git describe to get the current version, and figure out what the next version should be from the fragment types that are present, based on that naming scheme.

The only disadvantage I see with this approach is the burden on contributors, having to add those changelogs, and the big amount of commits like "Add changelog for PR X", since many people won't force-push, and you often can't know the PR number ahead of the time, as someone might create another PR taking it up, and since PR number is a part of the changelog file, that's something that can be a bit annoying when going through the git log. But it's nothing that terrible.

I wouldn't mind using towncrier here, I'd probably be able to set it up pretty quickly if desired, I'm just not sure if we want to have this additional burden added to contributors, it would be pretty neat if maintainers were able to do this instead. But I also don't see such a huge issue with conflicts and the annoyance you described with this specific approach.

**Comment by kevinkjt2000** [comment]
If the files are chunked and then later combined, that does avoid the
conflicts I described. However, I'm still against duplicating the
information in our code that is already tracked by git. Only one real
changelog is necessary and we already have a changelog via git's history on
the master branch. The only reason I don't accept GitHub's automatic
suggestions that come straight from git's history as-is during release
creation is that dependabot is too noisy and makes changes that don't
require a release. Adding numbered files with descriptions is an extra
burden to force on contributors when all I use is their PR titles. If a
change requires more than a one-liner description, I believe that warrants
its own documentation in the docs folder.

I may have spread confusion about my goal here. I'm suggesting we automate
the release process as it is today without changing the steps taken during
the process and this issue is aiming to automate one piece of that process
(tag created -> release to PyPi). The future suggestions are where I'm
pointing out potential automation that replaces the manual steps I've
outlined earlier. As it is now, there is no step in the process that
requires modification or creation of any file that duplicates what goes
into the version control's history, and automating the current process is
possible without adding such a step.

**Comment by ItsDrike** [comment]
> I may have spread confusion about my goal here. I'm suggesting we automate
the release process as it is today without changing the steps taken during
the process and this issue is aiming to automate one piece of that process
(tag created -> release to PyPi).

Ah, in that case the discussion about that is indeed not necessary to have within this issue, perhaps another issue would be worth opening about this once this is completed.

@kevinkjt2000 you're assigned the issue, so I assume you plan to work on this?
