### ISSUE TITLE
README.md documentation link open blank docs page

### ISSUE THREAD

**Issue by TiEmKej** [py-mine/mcstatus#534]
Would you change the link to "lastest" branch of docs, so readers wouldn't have to change it manually?

**Comment by PerchunPak** [comment]
There are no docs for v10 because they were added in unreleased v11. And we can't use docs from v11 for v10 because v11 changed public interfaces a lot (see #306 and #335).

Although, if you want to try new features - just use release candidate, it's pretty stable!
```
pip install mcstatus>=11.0.0rc1
```

---

Not closing this, because we probably should add some warning to stable tag.

**Comment by kevinkjt2000** [comment]
Nope, not changing the readme link because people kept coming into our Discord server saying that the "latest" docs were not matching up with the newest stable version which they thought was "latest".

A warning/disclaimer on stable for a short while wouldn't hurt. Another idea would be to rename "latest" on readthedocs to something like "pre-release" or "testing" to make it obvious that it is part of development still.

**Comment by PerchunPak** [comment]
> A warning/disclaimer on stable for a short while wouldn't hurt. Another idea would be to rename "latest" on readthedocs to something like "pre-release" or "testing" to make it obvious that it is part of development still.

Or just release another tag.

**Comment by kevinkjt2000** [comment]
What I was driving at is that "latest" is not a very descriptive label. Latest of what? stable? beta? from development? release on PyPi? I'd say that most people would assume "latest" corresponds with the latest released version and not realize that there are some pre-releases out at the moment since pip defaults to not installing pre-releases.

Of course once v11 is out, this naming scheme on readthedocs would matter less.

**Comment by PerchunPak** [comment]
Then, we can rename `latest` to `development` or `master`.

**Comment by ItsDrike** [comment]
Once v11 is out, the naming indeed wouldn't matter that much, and `latest` isn't that bad label when shown next to `stable`, most python documentation sites use these, so it's usually obvious what they are, but I wouldn't mind a rename to `development` if possible.

**Comment by kevinkjt2000** [comment]
Okay, I've made a temporary preview of what v10 docs could look like on this branch https://mcstatus.readthedocs.io/en/docs-on-v10/

If these are looking okay for v10, then I'll release a v10.0.4 version to promote these into "stable" on readthedocs. With plans to null-merge all of this into master via the backports branch that I also pushed, since many of these files have had significant changes in v11.

**Comment by ItsDrike** [comment]
The advanced usage shows `mcproto.dns` functions, which we determined weren't a part of the public API, and so they were removed later, they probably shouldn't be there. The entire advanced usage section can be removed, and the dns docs should be moved under internal data. You can probably cherry pick that off of some Perchunk Pak's commit, as I already requested this change in some PR before (though it might've been fixed via a force push instead).

**Comment by PerchunPak** [comment]
19e2446da8f985a591b9a5a3d754112634f130da
