### ISSUE TITLE
What is this? Is this a mod?

### ISSUE THREAD

**Issue by allanonmage** [py-mine/mcstatus#568]
I came across this while looking for a program to use on my private server to see if players were logged in so I could do maintenance on the server without waiting a minute or two for the client to launch.

This seems to be something for public servers? I'm not really sure what it's for tbh, which is why I'm here asking.  The docs page is empty btw.

I am a dev and an admin, so please, talk nerdy to me.

**Comment by ItsDrike** [comment]
Mcstatus is a project that allows you to obtain status information from minecraft servers. This is done by making the same kinds of requests that your minecraft client would make when you see the server in the multiplayer tab. So, you can use mcstatus to obtain the number of players on the server, the server MOTD, and some other things.

Mcstatus is NOT a mod nor a plugin, it's an external tool, that just obtains the status of a minecraft server running somewhere, it doesn't require that minecraft server to add mcstatus as a plugin, and it's also not a mod that you would need to add as a client.

You can use mcstatus from your terminal, for example you can enter this command, which will show you some information about how to use the CLI:  `python -m mcstatus --help` (that is, after you installed mcstatus of course). Mcstatus is written in python, and so you will need a python interpreter installed on your system to be able to run it. You can get one [here](https://www.python.org/downloads/)

>  The docs page is empty btw.

The documentation was only added recently, and because docs default to showing you a version from the last "stable" release, the page is empty. You can however select the "latest" version instead, which will show you the newly added documentation, but know that this documentation is for a pre-release, and so it's not applicable to the stable release you'd normally get by installing mcstatus.

![image](https://github.com/py-mine/mcstatus/assets/20902250/93b11d11-29a3-4c53-a795-b3c71d6bb3a5)
