### ISSUE TITLE
`JavaServer.lookup`: Uncaught exception `dns.resolver.LifetimeTimeout`

### ISSUE THREAD

**Issue by elmurato** [py-mine/mcstatus#648]
Hi there 👋 

In Home Assistant we are facing the [problem](https://github.com/home-assistant/core/issues/101545), that sometimes `dns.resolver.LifetimeTimeout` is raised while using the `lookup` function of `JavaServer`. It looks like resolving the SRV record times out, but `mcstatus` doesn't catch this exception
[here](https://github.com/py-mine/mcstatus/blob/db15ce72d6c52f1f5da44e9c774c11d3a67c9539/mcstatus/address.py#L219C6-L219C6):
```
try:
    host, port = mcstatus.dns.resolve_mc_srv(host, lifetime=lifetime)
except (dns.resolver.NXDOMAIN, dns.resolver.NoAnswer):
    if default_port is None:
        raise ValueError(
            f"Given address '{address}' doesn't contain port, doesn't have an SRV record pointing to a port,"
            " and default_port wasn't specified, can't parse."
        )
    port = default_port
```

Am I right? Thanks in advance.

**Comment by kevinkjt2000** [comment]
You are correct. Mcstatus does not catch every possible exception. Welcome to Python programming where you may need to catch some exceptions and deal with them in your own code.

Is there a reason you think this particular exception is an issue for mcstatus? Or is the DNS SRV record or DNS server perhaps configured incorrectly on your end?

**Comment by elmurato** [comment]
Thank you for your fast answer 👍 

For sure I can catch that exception within Home Assistant. But I think it would be cleaner, if `mcstatus` would handle that:
1) Since it's possible to set the `lifetime` argument, I was expecting that the API can also handle it.
2) In my case `dnspython` is an indirect dependency, therefore I would like to not start working with it.
3) If I only enter a hostname (which is not a SRV record) without a port, the SRV record resolver is always running and this exception is then potentially raised. So this affects both, hostname only addresses and SRV records.

In the linked problem the server of the user was offline at that time. I don't know if it was actually a SRV record or not. If this information is important please let me know. I can get that info.

**Comment by ItsDrike** [comment]
> 3. If I only enter a hostname (which is not a SRV record) without a port, the SRV record resolver is always running and this exception is then potentially raised. So this affects both, hostname only addresses and SRV records.

You don't need to use `lookup` in that case, if you're using an address that you know is already directly referring to the server where that minecraft server is running, you can always initialize the `JavaServer` class yourself, instead of using the `lookup` function (`s = mcstatus.JavaServer("myhost")`, leaving the port alone to assume the default value of 25565, or `s = mcstatus.JavaServer("myhost", 25565)`, specifying it directly, in case you'd want a non-default value). This function is here to mimic what minecraft client would do, if you entered this address into the multiplayer direct connect field.

> 1. Since it's possible to set the lifetime argument, I was expecting that the API can also handle it.

You can always set a higher timeout if you need to, for example you can use `JavaServer.lookup(address, timeout=8)` for 8 second timeouts instead of the default 3 second ones. What do you mean by the API can handle it? We do expose a way to set this lifetime from the lookup function, using the `timeout` argument.

> 2. In my case dnspython is an indirect dependency, therefore I would like to not start working with it.

All mcstatus could do is create a wrapper exception class to throw instead of the one from `dnspython`, however we would then need to mimic all of the possible the exception classes dnspython, and a bunch of other things (like sockets) can throw. There is a lot of such exceptions, and so it's not really viable for us to handle all of those. However I usually find the exceptions here relatively clear in telling you what's wrong. If you see a LifetimeTimeout, you should probably just set a bigger lifetime.

Although it is an interesting error to see, as it likely indicates that there's something wrong with your DNS server, it really shouldn't take longer than 3 seconds to resolve an SRV record here, so you might want to look into why it's taking that long.

**Comment by kevinkjt2000** [comment]
> 1. ...

Because of that, it is not possible for mcstatus to handle the exception gracefully. An API user could set a ridiculously low timeout and cause that lifetime exception to happen non-stop and what would mcstatus do in those cases? If you said raise an exception, you are correct! Exceptional behavior warrants raising exceptions.

> 2. ...

Python itself has plenty of exceptions in the base libraries, which are also indirect dependencies. I see no reason behind this argument on not catching exceptions in the application code given that Python is designed like this.

> 3. ...

Same as ItsDrike mentioned: skip using lookup if SRV is not desired.

Closing this, as I see no issue within mcstatus to fix. The solution here is to increase the timeout, improve the DNS setup that is perhaps faulty, avoid using the lookup function, or catch the exception in the application code.

**Comment by elmurato** [comment]
Thank you all for your detailed feedback, much appreciated 👍 

I would really like wrapper exceptions in `mcstatus`, but I also understand that this is a lot of effort with less benefit for you.

I'll try to catch the exception within Home Assistant then. I just wanted to check whether it can be handled in `mcstatus` first. 

And regarding not using lookup: I am relying on it since I don't know what the user enters in the address field. It can be anything (including SRV). And that's why lookup is perfect for that, same behavior as in the Minecraft client.
