### ISSUE TITLE
mcstatus cli: Motd is not JSON serializable

### ISSUE THREAD

**Issue by h7x4** [py-mine/mcstatus#825]
Not sure how much more there is to write about this, issue should be clear from the output.

Output:

```
$ mcstatus mc.hypixel.net json
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mcstatus/__main__.py", line 100, in main
    args.func(server)
  File "/usr/lib/python3.12/site-packages/mcstatus/__main__.py", line 51, in json
    print(json_dumps(data))
  File "/usr/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.12/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.12/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.12/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Motd is not JSON serializable
```

**Comment by ItsDrike** [comment]
Yeah, this is caused by #335 which rewritten how Motd is stored. There are multiple ways we could handle this due to how we represent motd now.

The easiest way to resolve this would be to just use `motd.raw` which also retains backwards compatibility and is matching with what minecraft actually returned.

The other option would be to customize the serialization to work with how the motd is represented by us in code now. This might be a bit nicer to work with for people, but is a breaking change.

**Comment by ItsDrike** [comment]
CC @PerchunPak

You opinion?

**Comment by PerchunPak** [comment]
For now, it is easier to just use `Motd.raw`, but the entire CLI part is pretty much outdated from how objects are represented internally, and in the ideal world CLI would be need to completely rewritten.

Though I am curious how much CLI is used, and I guess if it was broken for a year, it is not used by almost anyone, so I would like to remove it. It is hard to represent current internal objects with JSON.
